name: Publish

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-npm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
            scope: '@alexanderjeurissen'
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: npm publish --access public
          env:
            TAG: ${{ github.event.release.tag_name }}
            NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

  publish-gpr:
      needs: publish-npm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
            scope: '@alexanderjeurissen'
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
